---
version: 2

updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
    groups:
      all-dependencies:
        patterns:
          - "*"

  # Keep Docker base images up to date
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker
    groups:
      all-dependencies:
        patterns:
          - "*"
